config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  resources :items do
    get :upvote, on: :member
    get :expensive, on: :collection
  end

  match "admin/users_count" => "admin#users_count",via: [:get, :post]

  # match ':controller(/:action(/:id))(.:format)',via: [:get, :post]
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many   :positions
  has_many   :items, through: :positions
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polimorphic: true
end

app/models/item.rb
class Item < ActiveRecord::Base
    
    #  attr_accessible :price, :name, :real, :weight, :description
    
    validates :price, numericality: { greater_than: 0, allow_nil: true }
    validates :name, :description, presence: true
    
    after_initialize { puts "initialized" } # Item.new; Item.first
    after_save       { puts "saved" } # Item.save; Item.create; item.update_attributes()
    after_create     { puts "created" }
    after_update     { puts "updated" }
    after_destroy    { puts "destroyed" } # item.destroy
    
    has_many :positions
    has_many :carts, through: :positions
    has_many :comments, as: :commentable
    
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  belongs_to :user

  
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :login
  
  has_one :cart
  has_many :orders
  has_many :comments 
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :check_if_admin


  def users_count
    @users_count = User.count
    render layout: "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def render_403
    render file: "public/403.html", status: 403
  end
  
  def render_404
    render file: "public/404.html", status: 404
  end
   
  
  def check_if_admin
    render_403 unless params[:admin] 
  end
  
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :find_item,      only: [:show, :edit, :update, :destroy, :upvote]
#  before_filter :check_if_admin, only: [:edit, :update, :new, :create, :destrtoy]

  def index
      unless @items = Item.all
          render text: "page not found", status: 404
      end
  end

  # /items/1 GET
  def show
      unless @item
        render text: "page not found", status: 404
      end
  end

  # /items/new GET
  def new
    @item = Item.new
  end

  # items/1/edit GET
  def edit

  end

  # /items POST
  def create
    item_params = params.require(:item).permit(:name, :description, :price, :weight, :real)
    @item = Item.create(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item) #/items/:id
    else
      render "new"
    end
  end

  # /items/1 PUT
  def update
    item_params = params.require(:item).permit(:name, :description, :price, :weight, :real)
    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item) #/items/:id
    else
      render "edit"
    end
  end

  # /items/1 DELETE
  def destroy
    @item.destroy
    redirect_to action: "index"
  end

  def upvote
    @item.increment!(:votes_count)
    redirect_to action: :index
  end

  def expensive
    @items = Item.where("price > 1000")
    render "index"
  end

  private

    def find_item
      @item = Item.where(id: params[:id]).first
      render_404 unless @item

    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def urls_to_images(s)
    s.gsub! /\s(http:\/\/.*?\.(png|jpg))\s/, '<p><img src="\1"/><p>'
    s.html_safe
  end

  def urls_to_links(s)
    s.gsub! /\s(http:\/\/.*?)\s/, '<a href="\1">\1</a>'
    s.html_safe
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
There are <%= @users_count %> on the site.

app/views/items/_form.html.erb
<p>Цена</br> <%= f.text_field :price %></p>
<p>Название</br> <%= f.text_field :name %></p>
<p>Описание</br> <%= f.text_area :description %></p>
<p>Вес</br> <%= f.text_field :weight %></p>

app/views/items/edit.html.erb
<h1>Edit new item</h1>

  <%= form_for @item do |f| %>

  <%=render partial: "form", locals: {f: f}%>

	<p><%= f.submit %></p>

  <% end %>

app/views/items/index.html.erb
<h1>Items</h1>
<% if @items.empty?%>
	<b>No items in store</b>
<% else %>
<table>
	<tr>
		<th>item id</th>
		<th>Name</th>
		<th>Price</th>
		<th></th>
	</tr>
			
	<% @items.each do |i| %>

		<tr>
			<td><%= i.id %></td>
			<td><%= link_to i.name, item_path(i) %></td>
		    <td><%= i.price %>руб</td>
			<td><%= link_to "Удалить", item_path(i), method: :delete, data: { confirm: "Точно удалить?"} %></td>
			<td>Рейтинг: <%=i.votes_count%>, <%= link_to "+", upvote_item_path(i) %></td>
		    
		</tr>
	
	<% end %>

<% end %>

</table>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>

  <%=render partial: "form", locals: {f: f}%>

	<p><%= f.submit %></p>

<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<ul>
	<li><%= @item.id %></li>
    <li><%= @item.price %>руб</li>
    <li><%= urls_to_links(urls_to_images(@item.description)) %></li>
    <li>Вес:<%= @item.weight %></li>
	<li>Ссылка: <%= item_path(@item) %></li>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="adminPanel">
  Admin
</div>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>